name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  IMAGE_NAME: tungatarov/go-calculator
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tungatarov/go-calculator:$(date +%s)
      
    - uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.GITHUB_TOKEN }}  
   
    - name: Push Docker image
    - uses: docker/build-push-action@v2
      with:
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
